config/routes.rb
Rails.application.routes.draw do
  get 'index/home'
  get 'index/search'
  get 'index/about'
  get 'index/contact'
  root 'index#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users
  resources :microposts
  resource :replies
  resources :identities

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :replies
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1400 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # before_action :logged_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Post created successfully!"
    else
      flash[:error] = "Sorry! some errors."
    end
    redirect_to user_path(current_user)
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    redirect_to user_path(current_user)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<tr>
<td><%= image_tag(micropost.user.avatar_url(:thumb), class: 'img-circle') if micropost.user.avatar_url %></td>
<td><%= micropost.content %>
  <% if micropost.replies.any? %>
      <% @replies = micropost.replies  %>
      <table class="table">
      <%= render @replies %>
      </table>
  <% end %>
  <% if user_signed_in? %>
  <%= form_for(@reply) do |f| %>
      <%= f.hidden_field :micropost_id, value: micropost.id %>
      <%= f.text_area :content, placeholder: "Compose new reply...", class:'form-control' %>
      <br>
      <%= f.submit "Reply", class: "btn btn-primary" %>
  <% end %>
  <% end %>
</td>
<td><h5>Posted <%= time_ago_in_words micropost.created_at %> ago</h5>
  <% if current_user %>
    <%= link_to 'Delete',micropost_path(micropost.id), method: :delete %>
  <% end %>
</td>
</tr>

app/views/microposts/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= f.text_area :content, placeholder: "Compose new micropost...", class:'form-control' %>
    <br>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/microposts/create.js.erb
$('.result').html('<%= @result %>');