config/routes.rb
Rails.application.routes.draw do
  get 'index/home'
  get 'index/search'
  get 'index/about'
  get 'index/contact'
  root 'index#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users
  resources :microposts
  resource :replies
  resources :identities

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <%
     current_time = DateTime.now
  %>
  <span>&copy; <%= current_time.strftime "%Y" %> WorldPublico</span>
  <%= link_to 'About Us', index_about_path %>&nbsp;&nbsp;&nbsp;
  <%= link_to 'Contact', index_contact_path %>
</div>
</div>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>WorldPublico</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'favicon.png' %>


</head>
<body>
<%= render 'layouts/navbar'%>
<div class="container">

app/views/layouts/_navbar.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to image_tag('logo.jpg', class: 'logo-img'), root_path, class:"navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to '<span class="glyphicon glyphicon-home"></span> Home'.html_safe, root_url %></li>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> Account
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '<span class="glyphicon glyphicon-user"></span> Profile'.html_safe, user_path(current_user) %></li>
                <li><%= link_to '<span class="glyphicon glyphicon-edit"></span> Update'.html_safe, edit_user_path(current_user) %></li>
                <li><%= link_to '<span class="glyphicon glyphicon-log-out"></span> Log out'.html_safe, destroy_user_session_path, :method => :delete %></li>
                <li><%= link_to '<span class="glyphicon glyphicon-remove"></span> Delete'.html_safe, user_path(current_user), :method => :delete, 'data-confirm': 'Are you sure?' %></li>
              </ul>
            </li>
        <% else %>
            <li>
              <%=link_to '<span class="glyphicon glyphicon-user"></span> Login'.html_safe, new_user_session_path %>
            </li>
            <li>
              <%=link_to '<span class="glyphicon glyphicon-registration-mark"></span> Signup'.html_safe,  new_user_registration_path %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<%= render'layouts/header' %>
    <%= yield %>

<%= render'layouts/footer' %>